# Generated by Django 6.0.2 on 2026-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_is_reviewed_submission_is_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
    ]
