# Generated by Django 6.0.2 on 2026-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_is_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgefeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='winner_place',
            field=models.CharField(blank=True, choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place'), ('honorable_mention', 'Honorable Mention')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='winner_prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
