# Generated by Django 6.0.2 on 2026-03-16 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('team_join', 'Joined Team'), ('team_create', 'Created Team'), ('team_leave', 'Left Team'), ('submission', 'Submitted Project'), ('feedback', 'Received Feedback'), ('winner', 'Won Hackathon'), ('review', 'Submission Reviewed'), ('event_register', 'Registered for Event'), ('follow', 'Started Following'), ('new_follower', 'New Follower'), ('became_judge', 'Became a Judge'), ('became_organizer', 'Became an Organizer'), ('role_removed', 'Role Removed'), ('password_change', 'Password Changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
