# Generated by Django 6.0.2 on 2026-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_0013_event_judges_0013_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('team_join', 'Joined Team'), ('team_create', 'Created Team'), ('team_leave', 'Left Team'), ('submission', 'Submitted Project'), ('feedback', 'Received Feedback'), ('winner', 'Won Hackathon'), ('review', 'Submission Reviewed'), ('event_register', 'Registered for Event'), ('follow', 'Started Following'), ('new_follower', 'New Follower'), ('like', 'Post Liked'), ('repost', 'Post Reposted'), ('reply', 'Post Replied'), ('became_judge', 'Became a Judge'), ('became_organizer', 'Became an Organizer'), ('role_removed', 'Role Removed'), ('password_change', 'Password Changed')], max_length=50),
        ),
    ]
