# Generated by Django 6.0.2 on 2026-03-25 19:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_submission_judging_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='judging_criteria',
            field=models.JSONField(blank=True, default=core.models.default_judging_criteria),
        ),
    ]
