# Generated by Django 6.0.2 on 2026-03-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_eventsponsor_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('team_join', 'Joined Team'), ('team_create', 'Created Team'), ('team_leave', 'Left Team'), ('submission', 'Submitted Project'), ('feedback', 'Received Feedback'), ('winner', 'Won Hackathon'), ('review', 'Submission Reviewed'), ('event_register', 'Registered for Event'), ('follow', 'Started Following'), ('new_follower', 'New Follower'), ('like', 'Post Liked'), ('repost', 'Post Reposted'), ('reply', 'Post Replied'), ('moderation_warn', 'Account Warning'), ('moderation_suspend', 'Account Suspended'), ('moderation_ban', 'Account Banned'), ('became_judge', 'Became a Judge'), ('became_organizer', 'Became an Organizer'), ('role_removed', 'Role Removed'), ('password_change', 'Password Changed')], max_length=50),
        ),
    ]
